---
title: "DECISION_TREES_REGRESSION"
author: "LAVANYA B"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r}
youth_data=load("C:/Users/bunad/OneDrive/Desktop/SPRING 2024/MACHINE LEARNING 2/youth_data.Rdata")
youth_data=df
```


```{r}
cleaned_youth_data=na.omit(youth_data)

```

```{r}
library(dplyr)
cleaned_youth_data_subset_reg=df[,c(demographic_cols,youth_experience_cols,'iralcage')]
cleaned_youth_data_subset_reg <- cleaned_youth_data_subset_reg %>%
 filter(iralcage != 991)
nrow(cleaned_youth_data_subset_reg)
                                              
```

```{r}
train=sample(1:nrow(cleaned_youth_data_subset_reg),0.7*nrow(cleaned_youth_data_subset_reg))
training_data_reg=cleaned_youth_data_subset_reg[train,]
testing_data_reg=cleaned_youth_data_subset_reg[-train,]
```

```{r}
library(tree)
reg_tree=tree(iralcage ~.,data=training_data_reg)
plot(reg_tree)
text(reg_tree,pretty = 0)
reg_tree

```

```{r}
predict_reg=predict(reg_tree,testing_data_reg)
table(predict_reg,testing_data_reg$iralcage)
mean((predict_reg-testing_data_reg$iralcage)^2)
```

```{r}
cv_reg=cv.tree(reg_tree,FUN=prune.tree)
names(cv_reg)
cv_reg
                  
```
```{r}
par(mfrow = c(1, 2))
plot(cv_reg$size, cv_reg$dev, type = "b")
plot(cv_reg$k, cv_reg$dev, type = "b")

```

```{r}
prune_reg <- prune.tree(reg_tree, best = 4)
plot(prune_reg)
text(prune_reg, pretty = 0)

```

```{r}
prune_reg
```


```{r}
prune_reg_prediction = predict(prune_reg, testing_data_reg)
table(prune_reg_prediction, testing_data_reg$iralcage)
mean((prune_reg_prediction -testing_data_reg$iralcage)^2)

```
```{r}
missing_values=colSums(is.na(training_data_reg))
missing_values
```


# Bagging

```{r}
library(randomForest)
training_data_reg_clean=na.omit(training_data_reg)
bagging_reg <- randomForest(iralcage ~ ., data = training_data_reg_clean,
     mtry = floor(ncol(training_data_reg_clean)/3), importance = TRUE)
bagging_reg

```

```{r}
bagging_reg_prediction = predict(bagging_reg, newdata = testing_data_reg)

mean((bagging_reg_prediction-testing_data_reg$iralcage)^2,na.rm=TRUE)
```

```{r}
importance_bagging_reg <- importance(bagging_reg)
top_10 <- head(importance_bagging_reg, 10)
top_10

```
```{r}
varImpPlot(bagging_reg, n.var = 10, sort = TRUE, main = "Important variables of reg classification(Top 10)")

```


#Random Forest

```{r}
set.seed(1)
randomforest_reg <- randomForest(iralcage ~ ., data = training_data_reg_clean, mtry = floor(ncol(training_data_reg_clean)/3), importance = TRUE)
randomforest_reg

```

```{r}
yhat_randomforest_reg <- predict(randomforest_reg, newdata = testing_data_reg)
mean((yhat_randomforest_reg -testing_data_reg$iralcage)^2,na.rm=TRUE)
```

```{r}
importance_rf_reg <- importance(randomforest_reg)
top_10 <- head(importance_rf_reg, 10)
top_10

```


```{r}
varImpPlot(randomforest_reg, n.var = 10, sort = TRUE, main = "Important variables of reg classification(Top 10)")

```






